import { Router } from "express";
import US from "./users.services";
import * as UV from "./users.validation";
import validation from "../../middleware/validation.middleware";
import { Authentication } from "../../middleware/authentication.meddleware";
import { TokenType } from "../../utils/Security/Token";
const userRouter = Router();
userRouter.post("/signUp", validation(UV.signUpSchema), US.signUp);
userRouter.post("/login", validation(UV.logInSchema), US.logIn);
userRouter.patch("/confirmEmail",validation(UV.confirmEmailSchema), US.confirmEmail);
userRouter.get("/profile", Authentication(),US.getProfile);
userRouter.get("/logout", Authentication(),validation(UV.logOutSchema),US.logOut);
userRouter.get("/refreshtoken", Authentication(TokenType.refresh),US.refreshToken);
export default userRouter;
